/**
 * Rapido-style full-screen ride alert (driver app).
 *
 * WHAT IT DOES
 *   When a ride offer arrives while the app is not in the foreground, the
 *   phone's screen turns on and a full-screen offer appears OVER the lock
 *   screen — instead of only a heads-up banner a sleeping driver never sees.
 *
 * WHY IT IS LAUNCHED FROM JS RATHER THAN A CUSTOM FCM SERVICE
 *   The obvious design is a FirebaseMessagingService subclassing expo's
 *   ExpoFirebaseMessagingService (which is `open`, and registered at
 *   android:priority="-1" precisely to allow it). That was built and it does
 *   not compile: in SDK 54 expo modules are prebuilt artifacts, not Gradle
 *   projects — `gradlew projects` lists only :expo, :expo-modules-core,
 *   :expo-updates and its deps — so expo-notifications is not on the :app
 *   module's compile classpath and ExpoFirebaseMessagingService/RemoteMessage
 *   cannot be resolved there. (expo's own "uses `api` so they're visible to
 *   the app" comment applies only to the LEGACY autolinking path, which SDK 54
 *   does not use.) Chasing artifact coordinates would couple this to Expo
 *   internals that change between SDKs.
 *
 *   So the Activity is launched by JS through a private URL scheme instead.
 *   The Kotlin then needs only android.* classes: nothing to resolve, nothing
 *   that can break on an Expo upgrade.
 *
 *   Trade-off, stated plainly: this needs the JS process alive. In practice an
 *   ONLINE driver's app is alive — it runs a foreground location service, and
 *   offers only go to online drivers. If Android has fully killed the process,
 *   the driver still gets the ordinary high-priority notification with its
 *   Accept/Decline buttons, i.e. exactly today's behaviour. Strictly additive.
 *
 * BACKGROUND-LAUNCH LEGALITY
 *   Android 10+ blocks starting an Activity from the background unless the app
 *   holds SYSTEM_ALERT_WINDOW ("Display over other apps"). This app already
 *   requests that during onboarding and already describes it to drivers as
 *   "Ride popup appears on your locked screen" — the promise predates this
 *   implementation. If declined, the openURL call fails harmlessly.
 */
const { withDangerousMod, withAndroidManifest, AndroidConfig } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const PACKAGE = 'com.saurabhspero.rideappdriver';
const SCHEME = 'spperoalert';

// UI is built in code rather than XML on purpose: no new resource files, so
// nothing can clash with resources generated by Expo modules at build time.
const ACTIVITY_KT = `package ${PACKAGE}

import android.app.Activity
import android.content.Intent
import android.graphics.Color
import android.graphics.Typeface
import android.graphics.drawable.GradientDrawable
import android.os.Build
import android.os.Bundle
import android.os.Handler
import android.os.Looper
import android.util.TypedValue
import android.view.Gravity
import android.view.View
import android.view.ViewGroup
import android.view.WindowManager
import android.widget.LinearLayout
import android.widget.TextView

/**
 * Full-screen ride offer shown over the lock screen.
 *
 * Launched by JS via ${SCHEME}://ride?... — see withFullScreenRideAlert.js for
 * why it is not driven by a custom FCM service.
 *
 * Deliberately presentational: it makes NO API calls and never accepts a ride.
 * "Open & Accept" simply launches the app, landing on the existing, well-tested
 * offer screen. If anything here misbehaves the driver still has the ordinary
 * notification with its real Accept/Decline buttons.
 */
class RideAlertActivity : Activity() {

  private val autoDismiss = Handler(Looper.getMainLooper())

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    showOverLockScreen()
    setContentView(buildUi())

    // Offers expire server-side; don't leave a stale full-screen alert sitting
    // on a driver's phone after the offer is gone.
    autoDismiss.postDelayed({ if (!isFinishing) finish() }, 45_000)
  }

  // Launched again for a newer offer while still showing — replace, not stack.
  override fun onNewIntent(newIntent: Intent?) {
    super.onNewIntent(newIntent)
    setIntent(newIntent)
    setContentView(buildUi())
  }

  override fun onDestroy() {
    autoDismiss.removeCallbacksAndMessages(null)
    super.onDestroy()
  }

  private fun showOverLockScreen() {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O_MR1) {
      setShowWhenLocked(true)
      setTurnScreenOn(true)
    } else {
      @Suppress("DEPRECATION")
      window.addFlags(
        WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED or
          WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON
      )
    }
    // Deliberately NOT dismissing the keyguard: the offer is readable on the
    // lock screen, and the phone only unlocks if the driver chooses to open the
    // app. Silently unlocking someone's phone is not acceptable.
    window.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)
  }

  private fun dp(v: Int): Int = TypedValue.applyDimension(
    TypedValue.COMPLEX_UNIT_DIP, v.toFloat(), resources.displayMetrics
  ).toInt()

  private fun pill(bg: Int, label: String, fg: Int, onTap: () -> Unit): TextView =
    TextView(this).apply {
      text = label
      setTextColor(fg)
      textSize = 17f
      gravity = Gravity.CENTER
      setTypeface(typeface, Typeface.BOLD)
      setPadding(dp(18), dp(18), dp(18), dp(18))
      background = GradientDrawable().apply {
        cornerRadius = dp(16).toFloat()
        setColor(bg)
      }
      isClickable = true
      setOnClickListener { onTap() }
    }

  private fun param(key: String, fallback: String): String =
    try { intent?.data?.getQueryParameter(key)?.takeIf { it.isNotBlank() } ?: fallback }
    catch (_: Throwable) { fallback }

  private fun buildUi(): View {
    val kickerText = when {
      param("intercity", "false") == "true" -> "INTERCITY RIDE"
      param("scheduled", "false") == "true" -> "SCHEDULED RIDE"
      else -> "NEW RIDE REQUEST"
    }

    val root = LinearLayout(this).apply {
      orientation = LinearLayout.VERTICAL
      gravity = Gravity.CENTER
      setBackgroundColor(Color.parseColor("#160B29"))
      setPadding(dp(28), dp(40), dp(28), dp(40))
      layoutParams = ViewGroup.LayoutParams(
        ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT
      )
    }

    val kicker = TextView(this).apply {
      text = kickerText
      setTextColor(Color.parseColor("#FF2D78"))
      textSize = 13f
      letterSpacing = 0.18f
      gravity = Gravity.CENTER
      setTypeface(typeface, Typeface.BOLD)
    }

    val heading = TextView(this).apply {
      text = param("title", "New Ride Request")
      setTextColor(Color.WHITE)
      textSize = 27f
      gravity = Gravity.CENTER
      setTypeface(typeface, Typeface.BOLD)
      setPadding(0, dp(14), 0, 0)
    }

    val detail = TextView(this).apply {
      text = param("body", "A rider is waiting nearby.")
      setTextColor(Color.parseColor("#C9BFE0"))
      textSize = 16f
      gravity = Gravity.CENTER
      setPadding(0, dp(12), 0, dp(34))
    }

    val open = pill(Color.parseColor("#FF2D78"), "Open & Accept", Color.WHITE) {
      try {
        packageManager.getLaunchIntentForPackage(packageName)?.let {
          it.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
          it.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP)
          startActivity(it)
        }
      } catch (_: Throwable) {
      } finally {
        finish()
      }
    }

    val gap = View(this).apply {
      layoutParams = LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, dp(12))
    }

    val dismiss = pill(Color.parseColor("#2A1B45"), "Dismiss", Color.parseColor("#C9BFE0")) { finish() }

    val note = TextView(this).apply {
      text = "Accept / Decline are also on the notification"
      setTextColor(Color.parseColor("#7E7099"))
      textSize = 12f
      gravity = Gravity.CENTER
      setPadding(0, dp(18), 0, 0)
    }

    val wide = LinearLayout.LayoutParams(
      ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT
    )
    root.addView(kicker, wide)
    root.addView(heading, wide)
    root.addView(detail, wide)
    root.addView(open, wide)
    root.addView(gap)
    root.addView(dismiss, wide)
    root.addView(note, wide)
    return root
  }
}
`;

const withSources = (config) =>
  withDangerousMod(config, [
    'android',
    (cfg) => {
      const dir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app', 'src', 'main', 'java',
        ...PACKAGE.split('.')
      );
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, 'RideAlertActivity.kt'), ACTIVITY_KT);
      // Remove the abandoned FCM-service approach if a previous prebuild left
      // it behind — it does not compile (see the header comment).
      const stale = path.join(dir, 'RideAlertMessagingService.kt');
      if (fs.existsSync(stale)) fs.unlinkSync(stale);
      return cfg;
    },
  ]);

const withManifest = (config) =>
  withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);

    // Drop the service registration from the earlier approach, if present.
    if (app.service) {
      app.service = app.service.filter(
        (s) => s.$?.['android:name'] !== '.RideAlertMessagingService'
      );
    }

    app.activity = (app.activity || []).filter(
      (a) => a.$?.['android:name'] !== '.RideAlertActivity'
    );
    app.activity.push({
      $: {
        'android:name': '.RideAlertActivity',
        // Not exported: only this app may launch it. Same-app implicit intents
        // still resolve, so Linking.openURL works; other apps cannot poke it.
        'android:exported': 'false',
        // These two are what actually put it over the lock screen and light
        // the display up.
        'android:showWhenLocked': 'true',
        'android:turnScreenOn': 'true',
        // Own task, kept out of Recents — a transient alert, not something a
        // driver should be able to swipe back to later.
        'android:taskAffinity': '',
        'android:excludeFromRecents': 'true',
        'android:launchMode': 'singleTask',
        'android:screenOrientation': 'portrait',
        'android:theme': '@android:style/Theme.NoTitleBar.Fullscreen',
      },
      'intent-filter': [
        {
          action: [{ $: { 'android:name': 'android.intent.action.VIEW' } }],
          category: [
            { $: { 'android:name': 'android.intent.category.DEFAULT' } },
            { $: { 'android:name': 'android.intent.category.BROWSABLE' } },
          ],
          data: [{ $: { 'android:scheme': SCHEME } }],
        },
      ],
    });

    return cfg;
  });

module.exports = (config) => withManifest(withSources(config));
module.exports.SCHEME = SCHEME;
